language: python
sudo: true
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pip install pytest-cov
  - pipenv install
  - pip3 install -e .
script:
  - py.test --cov-report=xml --cov=flapjack tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
