language: python
sudo: true
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pipenv install
script:
  - py.test --cov-report=xml --cov=myproj tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
